######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 8 18:35:43 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
